plugins {
    id "com.android.application"
}

android {
    namespace "com.monster.cybershield"
    compileSdk 35

    defaultConfig {
        applicationId "com.monster.cybershield"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "0.1.0"
    }

    signingConfigs {
        release {
            storeFile file(System.properties["user.home"] + "/.android/debug.keystore")
            storePassword "android"
            keyAlias "androiddebugkey"
            keyPassword "android"
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            shrinkResources false
        }
    }

    aaptOptions {
        noCompress "tflite"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation "org.tensorflow:tensorflow-lite:2.16.1"
}
