#!/usr/bin/env python3
"""CyberShield model calibration gate.

This tool does not retrain models. It validates the shipped model catalog,
classifies each model's decision role, and writes a public-safe calibration
status report. It is intentionally conservative: models that have weak field
evidence or are support signals must not be presented as standalone blockers.
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path


SUPPORT_ONLY = {
    "android_malware_flow",
    "honeypot_threat_intel",
    "contextual_fraud_anomaly",
    "post_quantum_taxonomy",
    "post_quantum_subtype",
    "attack_anomaly",
}

FIELD_CALIBRATION_REQUIRED = {
    "wifi_threat",
    "mitm_arp",
    "post_quantum",
    "iot_attack",
}

ROUTING_ONLY = {
    "doh_l1",
}

PRIMARY_DETECTION = {
    "android_malware",
    "mirai",
    "network_attack",
    "dns_stateful",
    "doh_l2",
    "social_text",
    "social_url",
    "phishing_html",
    "stealth_phisher_2025",
}

DESTRUCTIVE_ACTIONS = {
    "uninstall_with_user_confirm",
    "uninstall_prompt",
}

HARD_BLOCK_ACTIONS = {
    "block_flow",
    "block_endpoint",
    "block_domain",
    "quarantine_network",
    "quarantine_message",
    "quarantine",
}


@dataclass
class Finding:
    severity: str
    model_id: str
    message: str


def role_for(model_id: str) -> str:
    if model_id in ROUTING_ONLY:
        return "routing_only"
    if model_id in SUPPORT_ONLY:
        return "support_only"
    if model_id in FIELD_CALIBRATION_REQUIRED:
        return "field_calibration_required"
    if model_id in PRIMARY_DETECTION:
        return "primary_detection"
    return "review_required"


def validate(repo: Path) -> tuple[list[dict], list[Finding]]:
    catalog_path = repo / "app" / "src" / "main" / "assets" / "model_catalog.json"
    root = json.loads(catalog_path.read_text(encoding="utf-8"))
    models = root.get("models", [])
    findings: list[Finding] = []
    rows: list[dict] = []

    if len(models) != 20:
        findings.append(Finding("fail", "catalog", f"expected 20 catalog models, found {len(models)}"))

    seen: set[str] = set()
    for model in models:
        model_id = model.get("id", "")
        role = role_for(model_id)
        asset = repo / "app" / "src" / "main" / "assets" / model.get("asset", "")
        interventions = set(model.get("interventions", []))
        accuracy = float(model.get("accuracy", 0.0))
        recall = float(model.get("recall", 0.0))

        if model_id in seen:
            findings.append(Finding("fail", model_id, "duplicate model id"))
        seen.add(model_id)

        if not asset.exists():
            findings.append(Finding("fail", model_id, f"missing asset: {model.get('asset')}"))

        if role in {"support_only", "routing_only"} and interventions & (HARD_BLOCK_ACTIONS | DESTRUCTIVE_ACTIONS):
            findings.append(Finding("fail", model_id, "support/routing model contains hard intervention"))

        if role == "field_calibration_required" and DESTRUCTIVE_ACTIONS & interventions:
            findings.append(Finding("fail", model_id, "field-calibrated model must not request destructive action"))

        if accuracy >= 0.9999 and model_id in FIELD_CALIBRATION_REQUIRED:
            findings.append(Finding("warn", model_id, "near-perfect dataset score; require field calibration evidence"))

        if accuracy < 0.70 and role != "support_only":
            findings.append(Finding("warn", model_id, "low accuracy outside support-only role"))

        rows.append(
            {
                "id": model_id,
                "title": model.get("title", model_id),
                "role": role,
                "asset_exists": asset.exists(),
                "input_size": model.get("input_size", 0),
                "accuracy": accuracy,
                "recall": recall,
                "interventions": sorted(interventions),
            }
        )
    return rows, findings


def write_report(repo: Path, rows: list[dict], findings: list[Finding]) -> None:
    out = repo / "docs" / "CALIBRATION_STATUS.md"
    fails = [f for f in findings if f.severity == "fail"]
    warns = [f for f in findings if f.severity == "warn"]
    lines = [
        "# CyberShield Calibration Status",
        "",
        "This report is generated by `tools/validate_model_calibration.py`.",
        "",
        "## Summary",
        "",
        f"- Catalog models checked: {len(rows)}",
        f"- Blocking findings: {len(fails)}",
        f"- Calibration warnings: {len(warns)}",
        "- Status: " + ("PASS" if not fails else "FAIL"),
        "",
        "## Decision Roles",
        "",
        "| Model | Role | Runtime use |",
        "| --- | --- | --- |",
    ]
    for row in rows:
        use = {
            "primary_detection": "Can raise user-visible intervention when corroborated by policy.",
            "field_calibration_required": "Can warn or increase protection after field/lab calibration.",
            "support_only": "Risk support signal only; no standalone hard blocking.",
            "routing_only": "Routes signal to another model; no direct alert.",
            "review_required": "Needs manual review before production claim.",
        }.get(row["role"], "Needs review.")
        lines.append(f"| `{row['id']}` | `{row['role']}` | {use} |")

    lines.extend(["", "## Findings", ""])
    if findings:
        for finding in findings:
            lines.append(f"- `{finding.severity}` `{finding.model_id}`: {finding.message}")
    else:
        lines.append("- No findings.")

    lines.extend(
        [
            "",
            "## Required External Evidence",
            "",
            "- AMTSO Android malware and phishing feature checks.",
            "- Benign URL/SMS/APK false-positive corpus.",
            "- DNS leak and VPN forwarding verification.",
            "- Wi-Fi MITM/ARP lab replay or controlled field capture.",
            "- 24-48 hour battery, RAM, CPU and network-load run.",
            "- OWASP MASVS/MASA-style independent review before production certification claims.",
            "",
            "This report is a calibration gate, not an independent certification.",
        ]
    )
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", default=".", help="Repository root")
    parser.add_argument("--write-report", action="store_true")
    args = parser.parse_args()

    repo = Path(args.repo).resolve()
    rows, findings = validate(repo)
    if args.write_report:
        write_report(repo, rows, findings)
    print(json.dumps({"models": len(rows), "findings": [f.__dict__ for f in findings]}, indent=2))
    return 1 if any(f.severity == "fail" for f in findings) else 0


if __name__ == "__main__":
    raise SystemExit(main())
